# Use Bun base image
FROM oven/bun:latest

# Set the working directory inside the container
WORKDIR /app

# Copy bun.lockb, and source code
COPY bun.lockb /app/
COPY . /app/

# Install dependencies and build the Vite project
RUN bun install && bun run build

# Expose the port for the Vite preview server
EXPOSE 5173

# Start the Vite dev server
CMD ["bun", "vite", "preview", "--host", "--port", "5173"]