# Use Bun base image
FROM oven/bun:latest

# Set the working directory inside the container
WORKDIR /app

# Copy bun.lockb, and source code
COPY bun.lockb /app/
COPY . /app/

# Install dependencies
RUN bun install

# Expose the port for the Vite dev server
EXPOSE 5173

# Start the Vite dev server
CMD ["bun", "vite", "--host", "--port", "5173"]